.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
.\" */
.\".
.TH "keentune-bench" "8" "5 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
KeenTune-bench - benchmark controlling components
.SH SYNOPSIS
\fBKeenTune-bench\fP
.SH DESCRIPTION
\fBKeenTune-bench\fR KeenTune-bench is a benchmark controlling components, which is deployed with benchmark tools. It is used in dynamic tuning workflows to run benchmark tools and get evalation metrics.

.SH "Run"
.
.TP
\fBsystemctl start keentune-bench.service\fR
.
.SH "benchmark"
.
.TP
Interaction data with keentuned using the tornado architecture. Parse the post request data and get the python file of benchmark and return the results after execution. Send the heartbeat packet data, and the keentuned process can detect the data.

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
                                                                                                                                                                                                1,1          顶端
